name: 컨테이너 기반 배포하기

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies, build and test
        run: |
          npm ci
          npm run build --if-present
          npm run test

      - name: Build Docker image
        run: |
          docker build -t web-server .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Log in to AWS ECR using AWS CLI
        env:
          ECR_REGISTRY_ID: ${{ secrets.ECR_REGISTRY_ID }}
          ECR_REGION: ap-northeast-2
        run: |
          aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin ${ECR_REGISTRY_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com

      - name: Tag and push Docker image
        env:
          ECR_REGISTRY_ID: ${{ secrets.ECR_REGISTRY_ID }}
        run: |
          docker tag web-server ${ECR_REGISTRY_ID}.dkr.ecr.ap-northeast-2.amazonaws.com/web-server:latest
          docker push ${ECR_REGISTRY_ID}.dkr.ecr.ap-northeast-2.amazonaws.com/web-server:latest

      - name: Debug ECR URL
        run: echo "${{ secrets.ECR_REGISTRY_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/web-server:latest"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script_stop: true
          script: |
            # docker stop web-server || true
            # docker rm web-server || true
            docker pull ${ECR_REGISTRY_ID}.dkr.ecr.ap-northeast-2.amazonaws.com/web-server:latest || true
            docker run -d --name web-server -p 80:80 ${ECR_REGISTRY_ID}.dkr.ecr.ap-northeast-2.amazonaws.com/web-server:latest
