name: 컨테이너 기반 배포하기

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies, build and test
        run: |
          npm ci
          npm run build --if-present
          npm run test

      - name: Build Docker image
        run: |
          docker build -t web-server .

      - name: Log in to AWS ECR Public
        id: login-ecr-public
        run: |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }} | docker login public.ecr.aws --username AWS --password-stdin

      - name: Tag and push Docker image
        run: |
          docker tag web-server public.ecr.aws/${{ secrets.AWS_ACCOUNT_ID }}/web-server:latest
          docker push public.ecr.aws/${{ secrets.AWS_ACCOUNT_ID }}/web-server:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script_stop: true
          script: |
            # docker stop web-server || true
            # docker rm web-server || true
            docker pull public.ecr.aws/${{ secrets.AWS_ACCOUNT_ID }}/web-server:latest
            docker run -d --name web-server -p 80:80 public.ecr.aws/${{ secrets.AWS_ACCOUNT_ID }}/web-server:latest
